export enum WorldCupCoreErrorCode {
  WC_SQUAD_UNAVAILABLE = 'WC_SQUAD_UNAVAILABLE',
  WC_TEAM_HISTORY_UNAVAILABLE = 'WC_TEAM_HISTORY_UNAVAILABLE',
  WC_SIMULATION_UNAVAILABLE = 'WC_SIMULATION_UNAVAILABLE',
  WC_SIMULATION_FETCH_FAILED = 'WC_SIMULATION_FETCH_FAILED',
  WC_JOURNEY_UNAVAILABLE = 'WC_JOURNEY_UNAVAILABLE',  // ← Codigo de error para journey nuevo
  WC_STATS_AWARDS_UNAVAILABLE = 'WC_STATS_AWARDS_UNAVAILABLE',  // ← NUEVO
}
